### ISSUE TITLE
Sample Usage

### ISSUE THREAD

**Issue by deshario** [wannaphongcom/lab-thai-ner#1]
พีครับ หลังจากผมติดตั้ง pip install pythainlp แล้วผมจะใช้มันได้ยังไงครับ พอจะมี documentation รึ code ตัวอย่างในการทำ name entity recognition มัยครับ ขอบคุณมากครับ

**Comment by wannaphong** [comment]
เอกสารตาม https://thainlp.org/pythainlp/docs/1.7/api/ner.html ครับ

**Comment by wannaphong** [comment]
อันนี้เป็นเอกสรในการทำ NER ครับ https://python3.wannaphong.com/2018/12/named-entity-recognition-ner-pythainlp.html
