### ISSUE TITLE
ช่วยแก้ไข tag ผิด ของ data.txt ของ version 1.0 นะครับ 

### ISSUE THREAD

**Issue by SuphanutN** [wannaphongcom/lab-thai-ner#3]
พอดี พบ tag ที่มีปัญหา 3 อันนี้ โดยชื่อ Tag ปิด ไม่ได้เป็น [/TAG] ครับ :)

1. ด้วยเหตุนี้กลุ่มธุรกิจพืชครบวงจร ซึ่งมีประสบการณ์ในการผลิตกล้ายางคุณภาพตามมาตรฐานของ[ORGANIZATION]**กรมวิชาการเกษตร**[ORGANIZATION]จากโครงการยางพารา 1 ล้านไร่ จึงทำการผลิตกล้ายางพันธุ์ดีพันธุ์ JVP80 เพื่อเป็นทางเลือกให้เกษตรกร เนื่องจากยางพันธุ์ JVP 80 มีความเข้มข้นของน้ำยางสูงถึง 46% และมีเปอร์เซ็นต์เนื้อยางแผ่นแหงสูงถึง 42-48% ตลอดจนให้ผลผลิตน้ำยางสูงถึงปีละ 450-500 กก./ไร่

2. และผลของการเก็บตัวอย่างรอบสองก็จะทยอยออกมาใน[TIME]**ช่วงเย็น**[TIME]ของวันอาทิตย์ที่ [DATE]15 กุมภาพันธ์[/DATE]นี้ ซึ่งจะได้ทราบกันว่ามีการตกค้างหรือกระจายอยู่ที่ไหน อย่างไร

3. [PERSON]นายธวัชชัย รัตนะพิสิฐ[/PERSON] ประธานคณะอนุกรรมการกลุ่มซูริมิและผลิตภัณฑ์ปลา[ORGANIZATION]สมาคมอาหารแช่เยือกแข็งไทย[/ORGANIZATION] กล่าวถึงสถานการณ์การส่งออกซูริมิว่า แนวโน้มราคาซูริมิตกต่ำต่อเนื่อง และผู้นำเข้า[LOCATION]ญี่ปุ่น[/LOCATION]ชะลอสั่งซื้อซูริมิจาก[LOCATION]**ไทย**[LOCATION] จึงมีการหารือในกลุ่มผู้ผลิต และมีมติของคณะอนุกรรมการฯ ว่า โรงงานซูริมิใน[LOCATION]ไทย[/LOCATION] จะมีการควบคุมปริมาณการผลิตซูริมิให้ลดลงจนถึง[DATE]สิ้นปีนี้[/DATE] หรืออาจถึงไตรมาส 1 [DATE]ปีหน้า[/DATE] ซึ่งสอดคล้องกับในช่วงนี้เนื่องจากเป็นช่วงฤดูมรสุม ทำให้เรือประมงจับปลาได้น้อยลง และเน้นการจับปลาและหมึกที่มีมูลค่ามากกว่าแทน เรือประมงบางส่วนเห็นว่าการออกเรือแต่ละเที่ยวขาดทุน เพราะจับปลาได้น้อย จึงมีการจอดเทียบท่าและซ่อมแซมเรือ เพื่อเตรียมเรือไว้ใช้ในช่วงหมดฤดูมรสุม ทำให้ปริมาณปลาเข้าตลาดน้อยลง ในส่วนราคาปลาป่นมีแนวโน้มลดต่ำลงเช่นกัน เนื่องจากโรงงานอาหารสัตว์ได้นำเข้าเนื้อป่น และกระดูกป่น ซึ่งมีการปรับลดภาษีนำเข้าจากการทำ FTA เข้ามาทดแทนปลาป่นเฉลี่ยเดือนละถึง 15,000 ตัน โดยเฉพาะในเดือน[DATE]ตุลาคม 2551[/DATE]

**Comment by wannaphong** [comment]
แก้ไขแล้วครับ ใน version 1.1 จะปล่อยที่แก้ไขแล้วออกมาครับ
